pipeline {
    agent any
    environment {
        def myVar = "Hello World"
    }

    stages {
        stage("Demo") {
            steps {
                myFunction()
            }
        }
    }
}

def myFunction() {
    echo "The global variable is ${myVar}"
}