pipeline {
    agent any
    environment {
        def myVar = "The variable declared under environment is global"
    }

    stages {
        stage("Demo") {
            steps {
                echo "The global variable is ${myVar}"
            }
        }
    }
}