pipeline {
    agent any
    stages {
        stage('Clean Up') {
            steps {
                deleteDir()
                echo 'hi'
            }
        }
        stage('Clone Repo') {
            steps {
                sh 'git clone https://github.com/jenkins-docs/simple-java-maven-app.git'
            }
        }
        stage('Build') {
            steps {
                dir('simple-java-maven-app') {
                    sh 'mvn clean install'
                }
            }
        }
        stage('Test') {
            steps {
                dir('simple-java-maven-app') {
                    sh 'mvn test'
                }
            }
        }
        stage('Build remote') {
            steps {
                build job: 'booleanPipeline', parameters: [[$class: 'BooleanParameterValue', name: "myBoolean", value: true ]]
            }
        }
    }
}
